name: bookshelf
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.5.0
  flutter_riverpod: ^2.5.3
  intl: ^0.19.0
  gap: ^3.0.1
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
