/// Generated by one_line_text_style package

import 'package:flutter/material.dart';

const ts = TextStyle(
  fontSize: 14,
  color: Colors.black,
);

extension SizeExtension on TextStyle {

  TextStyle get size8 => copyWith(
    fontSize: 8,
  );

  TextStyle get size10 => copyWith(
    fontSize: 10,
  );

  TextStyle get size12 => copyWith(
    fontSize: 12,
  );

  TextStyle get size14 => copyWith(
    fontSize: 14,
  );

  TextStyle get size16 => copyWith(
    fontSize: 16,
  );

  TextStyle get size18 => copyWith(
    fontSize: 18,
  );

  TextStyle get size20 => copyWith(
    fontSize: 20,
  );

  TextStyle get size22 => copyWith(
    fontSize: 22,
  );

  TextStyle get size24 => copyWith(
    fontSize: 24,
  );

  TextStyle get size26 => copyWith(
    fontSize: 26,
  );

  TextStyle get size28 => copyWith(
    fontSize: 28,
  );

  TextStyle get size30 => copyWith(
    fontSize: 30,
  );

  TextStyle get size32 => copyWith(
    fontSize: 32,
  );

  TextStyle get size34 => copyWith(
    fontSize: 34,
  );

  TextStyle get size36 => copyWith(
    fontSize: 36,
  );

  TextStyle get size38 => copyWith(
    fontSize: 38,
  );

  TextStyle get size40 => copyWith(
    fontSize: 40,
  );

  TextStyle get size42 => copyWith(
    fontSize: 42,
  );

  TextStyle get size44 => copyWith(
    fontSize: 44,
  );

  TextStyle get size46 => copyWith(
    fontSize: 46,
  );

  TextStyle get size48 => copyWith(
    fontSize: 48,
  );

  TextStyle get size50 => copyWith(
    fontSize: 50,
  );

  TextStyle get size52 => copyWith(
    fontSize: 52,
  );

  TextStyle get size54 => copyWith(
    fontSize: 54,
  );

  TextStyle get size56 => copyWith(
    fontSize: 56,
  );

  TextStyle get size58 => copyWith(
    fontSize: 58,
  );

  TextStyle get size60 => copyWith(
    fontSize: 60,
  );

}

extension WeightExtension on TextStyle {

  TextStyle get w100 => copyWith(
    fontWeight: FontWeight.w100,
  );

  TextStyle get w200 => copyWith(
    fontWeight: FontWeight.w200,
  );

  TextStyle get w300 => copyWith(
    fontWeight: FontWeight.w300,
  );

  TextStyle get w400 => copyWith(
    fontWeight: FontWeight.w400,
  );

  TextStyle get w500 => copyWith(
    fontWeight: FontWeight.w500,
  );

  TextStyle get w600 => copyWith(
    fontWeight: FontWeight.w600,
  );

  TextStyle get w700 => copyWith(
    fontWeight: FontWeight.w700,
  );

  TextStyle get w800 => copyWith(
    fontWeight: FontWeight.w800,
  );

  TextStyle get w900 => copyWith(
    fontWeight: FontWeight.w900,
  );

  TextStyle get semibold => copyWith(
    fontWeight: FontWeight.w600,
  );

  TextStyle get bold => copyWith(
    fontWeight: FontWeight.w700,
  );

}

extension ColorExtension on TextStyle {

  TextStyle get white => copyWith(
    color: const Color(0xFFFFFFFF),
  );

  TextStyle get black => copyWith(
    color: const Color(0xFF000000),
  );

  TextStyle get grey => copyWith(
    color: const Color(0xFF9E9E9E),
  );

  TextStyle get red => copyWith(
    color: const Color(0xFFF44336),
  );

}

extension FontFamilyExtension on TextStyle {
}

extension StyleExtension on TextStyle {

  TextStyle get italic => copyWith(
    fontStyle: FontStyle.italic,
  );

}

extension DecorationExtension on TextStyle {

  TextStyle get underline => copyWith(
    decoration: TextDecoration.underline,
  );

  TextStyle get overline => copyWith(
    decoration: TextDecoration.overline,
  );

  TextStyle get lineThrough => copyWith(
    decoration: TextDecoration.lineThrough,
  );

}

extension DecorationStyleExtension on TextStyle {

  TextStyle get solid => copyWith(
    decorationStyle: TextDecorationStyle.solid,
  );

  TextStyle get double => copyWith(
    decorationStyle: TextDecorationStyle.double,
  );

  TextStyle get dotted => copyWith(
    decorationStyle: TextDecorationStyle.dotted,
  );

  TextStyle get dashed => copyWith(
    decorationStyle: TextDecorationStyle.dashed,
  );

  TextStyle get wavy => copyWith(
    decorationStyle: TextDecorationStyle.wavy,
  );

}

extension OverflowExtension on TextStyle {

  TextStyle get overflowClip => copyWith(
    overflow: TextOverflow.clip,
  );

  TextStyle get overflowFade => copyWith(
    overflow: TextOverflow.fade,
  );

  TextStyle get overflowEllipsis => copyWith(
    overflow: TextOverflow.ellipsis,
  );

  TextStyle get overflowVisible => copyWith(
    overflow: TextOverflow.visible,
  );

}
